[package]
name = "secure-mta"
version = "0.0.0"
authors = ["hyperfekt <adni.online@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.9", default-features = true }